### ISSUE TITLE
Error: fail to retrieve pull request from GitHub

### ISSUE THREAD

**Issue by ashleyconnor** [ldez/prm#18]
Hey,

I'm attempting to use this with Github Enterprise but I'm running into the following issue:

```console
➜  my-repo git:(my-branch) prm
? Choose the action checkout
git remote --verbose
2019/07/08 10:43:24 Error: fail to retrieve pull request from GitHub: GET https://github.bigbank.com/repos/org/my-repo/pulls?per_page=50&state=open: 404  []
```
```
prm:
 version     : 2.6.0
 commit      : e1679c16a1f7f6f3ac6323f4359201c391b9fb68
 build date  : 2019-07-08T00:07:47Z
 go version  : go1.12.6
 go compiler : gc
 platform    : darwin/amd64
```

Dropping the `/repos/` from the URL I can resolve that address in a browser.

GitHub Enterprise Server 2.16.9.

Thanks.

**Comment by ldez** [comment]
Hello,

The URL is built by the GitHub client itself.

I don't use GitHub Enterprise, so I cannot debug this point, but `PRM_GITHUB_API_BASE_URL` must be the "domain endpoint", I think it's an specific URL to the API of GitHub Enterprise.

Could your check your `PRM_GITHUB_API_BASE_URL`?

**Comment by ashleyconnor** [comment]
I think you are right. I used the web URL rather than the API URL. I'll report back once I get a chance to test.

**Comment by ashleyconnor** [comment]
Changing `PRM_GITHUB_API_BASE_URL` from `https://github.bigbank.com/` to `https://github.bigbank.com/api/v3/` resolved the issue.

Would you be open to a small change to the docs to replace `XXXXXXXXX` to `https://example.com/api/v3` [here](https://github.com/ldez/prm/blob/master/docs/content/main.md#prm_github_api_base_url)? I probably would have caught it if had I saw that.

**Comment by ldez** [comment]
Great.

I will be happy if you create PR to improve the documentation.
